In [1]:
import pandas as pd

df = pd.read_csv("Telco_Customer_Churn_Dataset.csv")

In [2]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [3]:
print(df.columns.tolist())

['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [4]:
df.shape

(7043, 21)

rows=7043
columns=21

In [5]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

 -The TotalCharges variable is stored as an object and requires further preprocessing before modeling
 -target variable Churn is categorical and will need to be encoded for machine learning purposes

In [7]:
df['TotalCharges'].head()

0      29.85
1     1889.5
2     108.15
3    1840.75
4     151.65
Name: TotalCharges, dtype: object

In [8]:
print(df['TotalCharges'].unique()[:20])

['29.85' '1889.5' '108.15' '1840.75' '151.65' '820.5' '1949.4' '301.9'
 '3046.05' '3487.95' '587.45' '326.8' '5681.1' '5036.3' '2686.05'
 '7895.15' '1022.95' '7382.25' '528.35' '1862.9']

In [9]:
df['TotalCharges'].apply(type).value_counts()

TotalCharges
<class 'str'>    7043
Name: count, dtype: int64

TotalCharges is stored as object/string type due to inconsistent values or missing entries and requires conversion to numeric type before modeling.”

In [10]:
print(df['TotalCharges'].dtype)

object

In [11]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [12]:
print(df['TotalCharges'].dtype)

float64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [14]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [15]:
print("dtype:", df['TotalCharges'].dtype)
print("missing:", df['TotalCharges'].isnull().sum())
print("sample:", df['TotalCharges'].head())

dtype: float64
missing: 11
sample: 0      29.85
1    1889.50
2     108.15
3    1840.75
4     151.65
Name: TotalCharges, dtype: float64

In [16]:
df['TotalCharges'] = df['TotalCharges'].fillna(0)

In [17]:
print("dtype :", df['TotalCharges'].dtype)
print("missing:", df['TotalCharges'].isnull().sum())
print("\nAll missing values:")
print(df.isnull().sum())

dtype : float64
missing: 0

All missing values:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

no missing value

know encoding

In [18]:
# Backup clean state
churn_df_copy = df.copy()

print("Backup:", churn_df_copy.shape)
print("Working df:", df.shape)

Backup: (7043, 21)
Working df: (7043, 21)

In [19]:
churn_df_copy.drop(columns=['customerID'], inplace=True)

print("Shape:", churn_df_copy.shape)
print("Colonnes:", churn_df_copy.columns.tolist())

Shape: (7043, 20)
Colonnes: ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [20]:
 churn_df_copy.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [21]:
for col in  churn_df_copy.select_dtypes(include='object').columns:
    print(col)
    print(df[col].unique())
    print("-"*40)

gender
['Female' 'Male']
----------------------------------------
Partner
['Yes' 'No']
----------------------------------------
Dependents
['No' 'Yes']
----------------------------------------
PhoneService
['No' 'Yes']
----------------------------------------
MultipleLines
['No phone service' 'No' 'Yes']
----------------------------------------
InternetService
['DSL' 'Fiber optic' 'No']
----------------------------------------
OnlineSecurity
['No' 'Yes' 'No internet service']
----------------------------------------
OnlineBackup
['Yes' 'No' 'No internet service']
----------------------------------------
DeviceProtection
['No' 'Yes' 'No internet service']
----------------------------------------
TechSupport
['No' 'Yes' 'No internet service']
----------------------------------------
StreamingTV
['No' 'Yes' 'No internet service']
----------------------------------------
StreamingMovies
['No' 'Yes' 'No internet service']
----------------------------------------
Contract
['Month-to-month' 'One year' 'Two year']
----------------------------------------
PaperlessBilling
['Yes' 'No']
----------------------------------------
PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
----------------------------------------
Churn
['No' 'Yes']
----------------------------------------

In [22]:
churn_df_encoded = pd.get_dummies(
    churn_df_copy,
    drop_first=True
)

In [23]:
churn_df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7043 non-null   int64
 1   tenure                                 7043 non-null   int64
 2   MonthlyCharges                         7043 non-null   float64
 3   TotalCharges                           7043 non-null   float64
 4   gender_Male                            7043 non-null   bool
 5   Partner_Yes                            7043 non-null   bool
 6   Dependents_Yes                         7043 non-null   bool
 7   PhoneService_Yes                       7043 non-null   bool
 8   MultipleLines_No phone service         7043 non-null   bool
 9   MultipleLines_Yes                      7043 non-null   bool
 10  InternetService_Fiber optic            7043 non-null   bool
 11  InternetService_No                     7043 non-null   bool
 12  OnlineSecurity_No internet service     7043 non-null   bool
 13  OnlineSecurity_Yes                     7043 non-null   bool
 14  OnlineBackup_No internet service       7043 non-null   bool
 15  OnlineBackup_Yes                       7043 non-null   bool
 16  DeviceProtection_No internet service   7043 non-null   bool
 17  DeviceProtection_Yes                   7043 non-null   bool
 18  TechSupport_No internet service        7043 non-null   bool
 19  TechSupport_Yes                        7043 non-null   bool
 20  StreamingTV_No internet service        7043 non-null   bool
 21  StreamingTV_Yes                        7043 non-null   bool
 22  StreamingMovies_No internet service    7043 non-null   bool
 23  StreamingMovies_Yes                    7043 non-null   bool
 24  Contract_One year                      7043 non-null   bool
 25  Contract_Two year                      7043 non-null   bool
 26  PaperlessBilling_Yes                   7043 non-null   bool
 27  PaymentMethod_Credit card (automatic)  7043 non-null   bool
 28  PaymentMethod_Electronic check         7043 non-null   bool
 29  PaymentMethod_Mailed check             7043 non-null   bool
 30  Churn_Yes                              7043 non-null   bool
dtypes: bool(27), float64(2), int64(2)
memory usage: 405.9 KB

In [24]:
churn_df_encoded.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,True,False,False,True,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,True,False,True,False,True

In [25]:
from sklearn.model_selection import train_test_split

X = churn_df_encoded.drop('Churn_Yes', axis=1)

y = churn_df_encoded['Churn_Yes']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [26]:
import os
os.makedirs("C:/Users/hp/Desktop/Intern", exist_ok=True)

In [28]:
churn_df_encoded.to_csv(
    "C:/Users/hp/Desktop/Intern/churn_df_encoded.csv",
    index=False
)

In [31]:
 churn_df_copy.to_csv(
    "C:/Users/hp/Desktop/Intern/churn_df_copy.csv",
    index=False
 )